services:
  - type: web
    name: hackrx-api
    runtime: python
    buildCommand: pip install -r requirements.txt  # Add this!
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        value: sk-spgw-api01-7725518cecd9cb0663448e4489e7693f
    plan: free
